# Development override for docker-compose.yml
# Usage: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up
# This file provides development-specific overrides for the multi-container setup

services:
  # Override migration service for development
  migration:
    # No specific overrides needed for migration in dev
    environment:
      - DEBUG=True
    volumes:
      - ./app:/app  # Live code reloading for migration files

  # Override Django service for development
  django:
    # Use development server instead of gunicorn for auto-reload
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    environment:
      # Override with development-specific settings
      - DEBUG=True
      - DJANGO_DEBUG=True
      - DJANGO_LOG_LEVEL=DEBUG
      - ALLOWED_HOSTS=localhost,127.0.0.1,django,notipus_django
    # Enable live code reloading for development
    volumes:
      - ./app:/app
      - static_volume:/app/staticfiles

  # Keep db healthcheck enabled since migration depends on it
  # Only disable nginx healthcheck for faster startup
  nginx:
    healthcheck:
      disable: true