# Generated by Django 5.2.10 on 2026-01-28 08:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0018_add_zendesk_integration_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrossReferenceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup_type', models.CharField(choices=[('shopify_to_chargify', 'Shopify Order to Chargify Payment'), ('chargify_to_shopify', 'Chargify Payment to Shopify Order')], max_length=30)),
                ('source_ref', models.CharField(max_length=255)),
                ('target_ref', models.CharField(blank=True, default='', max_length=255)),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['lookup_type', 'source_ref'], name='webhooks_cr_lookup__b38b2d_idx'), models.Index(fields=['created_at'], name='webhooks_cr_created_b9fe8a_idx')],
            },
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('chargify', 'Chargify'), ('stripe', 'Stripe'), ('shopify', 'Shopify')], max_length=20)),
                ('external_id', models.CharField(max_length=255)),
                ('customer_id', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending'), ('cancelled', 'Cancelled')], max_length=20)),
                ('shopify_order_ref', models.CharField(blank=True, default='', max_length=255)),
                ('chargify_transaction_id', models.CharField(blank=True, default='', max_length=255)),
                ('stripe_payment_intent_id', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('processed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['customer_id'], name='webhooks_pa_custome_deb283_idx'), models.Index(fields=['shopify_order_ref'], name='webhooks_pa_shopify_1f72ab_idx'), models.Index(fields=['chargify_transaction_id'], name='webhooks_pa_chargif_bfe49e_idx'), models.Index(fields=['stripe_payment_intent_id'], name='webhooks_pa_stripe__c97c32_idx'), models.Index(fields=['processed_at'], name='webhooks_pa_process_ef2349_idx')],
                'unique_together': {('provider', 'external_id')},
            },
        ),
        migrations.CreateModel(
            name='OrderRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('shopify', 'Shopify')], max_length=20)),
                ('external_id', models.CharField(max_length=255)),
                ('order_number', models.CharField(blank=True, default='', max_length=255)),
                ('customer_id', models.CharField(max_length=255)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('order_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_orders', to='webhooks.paymentrecord')),
            ],
            options={
                'indexes': [models.Index(fields=['customer_id'], name='webhooks_or_custome_9ad997_idx'), models.Index(fields=['order_number'], name='webhooks_or_order_n_da0e2d_idx'), models.Index(fields=['order_date'], name='webhooks_or_order_d_01471e_idx')],
                'unique_together': {('platform', 'external_id')},
            },
        ),
        migrations.CreateModel(
            name='SlackThreadMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('zendesk_ticket', 'Zendesk Ticket'), ('shopify_order', 'Shopify Order'), ('stripe_subscription', 'Stripe Subscription'), ('chargify_subscription', 'Chargify Subscription')], max_length=50)),
                ('entity_id', models.CharField(max_length=255)),
                ('slack_channel_id', models.CharField(max_length=50)),
                ('slack_thread_ts', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_mappings', to='core.workspace')),
            ],
            options={
                'verbose_name': 'Slack Thread Mapping',
                'verbose_name_plural': 'Slack Thread Mappings',
                'indexes': [models.Index(fields=['workspace', 'entity_type', 'entity_id'], name='webhooks_sl_workspa_e3f720_idx'), models.Index(fields=['slack_channel_id', 'slack_thread_ts'], name='webhooks_sl_slack_c_220b9a_idx'), models.Index(fields=['created_at'], name='webhooks_sl_created_cf7d85_idx')],
                'unique_together': {('workspace', 'entity_type', 'entity_id')},
            },
        ),
    ]
