# Generated by Django 5.1.6 on 2025-04-01 16:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UsageLimit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("trial", "14-Day Trial"),
                            ("basic", "Basic ($20/month)"),
                            ("pro", "Pro ($50/month)"),
                            ("enterprise", "Enterprise ($200/month)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("max_monthly_registrations", models.IntegerField()),
                ("max_daily_webhooks", models.IntegerField()),
                ("features", models.JSONField(default=list)),
            ],
        ),
        migrations.AddField(
            model_name="organization",
            name="billing_cycle_anchor",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="payment_method_added",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="organization",
            name="stripe_customer_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="organization",
            name="subscription_plan",
            field=models.CharField(
                choices=[
                    ("trial", "14-Day Trial"),
                    ("basic", "Basic ($20/month)"),
                    ("pro", "Pro ($50/month)"),
                    ("enterprise", "Enterprise ($200/month)"),
                ],
                default="trial",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="subscription_status",
            field=models.CharField(default="active", max_length=20),
        ),
        migrations.AddField(
            model_name="organization",
            name="trial_end_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 4, 15, 16, 43, 41, 135860, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
