# Generated by Django 5.2.10 on 2026-01-20 11:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_populate_initial_plans"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={"verbose_name_plural": "Companies"},
        ),
        migrations.AddField(
            model_name="company",
            name="brand_info",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="company",
            name="logo_url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
