# Generated by Django 5.1.6 on 2025-04-20 09:54

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_organization_shop_domain_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domain", models.CharField(max_length=255, unique=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("logo_url", models.URLField(blank=True, null=True)),
                ("brand_info", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name="organization",
            name="trial_end_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 5, 4, 9, 54, 7, 613444, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
