# Generated by Django 5.2.10 on 2026-01-22 20:13

from django.db import migrations, models


def create_free_plan(apps, schema_editor):
    """Create the free plan with 20 events per month."""
    Plan = apps.get_model("core", "Plan")

    Plan.objects.get_or_create(
        name="free",
        defaults={
            "display_name": "Free Plan",
            "description": "Get started with 20 events per month, free forever",
            "price_monthly": 0.00,
            "price_yearly": 0.00,
            "max_users": 1,
            "max_integrations": 1,
            "max_monthly_notifications": 20,
            "features": [
                "20 events/month",
                "1 integration",
                "Community support",
            ],
            "stripe_price_id_monthly": "",
            "stripe_price_id_yearly": "",
            "is_active": True,
        },
    )


def remove_free_plan(apps, schema_editor):
    """Remove the free plan."""
    Plan = apps.get_model("core", "Plan")
    Plan.objects.filter(name="free").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_add_company_brand_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="subscription_plan",
            field=models.CharField(
                choices=[
                    ("free", "Free Plan"),
                    ("trial", "14-Day Trial"),
                    ("basic", "Basic Plan - $29/month"),
                    ("pro", "Pro Plan - $99/month"),
                    ("enterprise", "Enterprise Plan - $299/month"),
                ],
                default="trial",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="usagelimit",
            name="plan",
            field=models.CharField(
                choices=[
                    ("free", "Free Plan"),
                    ("trial", "14-Day Trial"),
                    ("basic", "Basic Plan - $29/month"),
                    ("pro", "Pro Plan - $99/month"),
                    ("enterprise", "Enterprise Plan - $299/month"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="webauthnchallenge",
            name="challenge_type",
            field=models.CharField(
                choices=[
                    ("registration", "Registration"),
                    ("authentication", "Authentication"),
                    ("signup_registration", "Signup Registration"),
                ],
                max_length=20,
            ),
        ),
        migrations.RunPython(create_free_plan, remove_free_plan),
    ]
