# Generated by Django 5.1.6 on 2025-04-20 10:00

from django.db import migrations, models
from django.utils import timezone


def get_trial_end_date():
    """Returns a trial end date 14 days from now"""
    return timezone.now() + timezone.timedelta(days=14)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_company_alter_organization_trial_end_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="trial_end_date",
            field=models.DateTimeField(default=get_trial_end_date),
        ),
    ]
