# Generated by Django 5.2.10 on 2026-01-23 08:52

import uuid

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_allow_null_shop_domain'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Step 1: Rename the Organization model to Workspace first
        migrations.RenameModel(
            old_name='Organization',
            new_name='Workspace',
        ),
        # Step 2: Rename OrganizationUser to WorkspaceMember
        migrations.RenameModel(
            old_name='OrganizationUser',
            new_name='WorkspaceMember',
        ),
        # Step 3: Rename FK fields to use 'workspace' instead of 'organization'
        migrations.RenameField(
            model_name='integration',
            old_name='organization',
            new_name='workspace',
        ),
        migrations.RenameField(
            model_name='notificationsettings',
            old_name='organization',
            new_name='workspace',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='organization',
            new_name='workspace',
        ),
        migrations.RenameField(
            model_name='workspacemember',
            old_name='organization',
            new_name='workspace',
        ),
        # Step 4: Update constraints
        migrations.AlterUniqueTogether(
            name='integration',
            unique_together={('workspace', 'integration_type')},
        ),
        migrations.AlterUniqueTogether(
            name='workspacemember',
            unique_together={('user', 'workspace')},
        ),
        # Step 5: Update role choices for WorkspaceMember (owner, admin, user)
        migrations.AlterField(
            model_name='workspacemember',
            name='role',
            field=models.CharField(
                choices=[('owner', 'Owner'), ('admin', 'Admin'), ('user', 'User')],
                default='user',
                max_length=20,
            ),
        ),
        # Step 6: Set explicit db_table names (preserves existing table names)
        migrations.AlterModelTable(
            name='workspace',
            table='core_organization',
        ),
        migrations.AlterModelTable(
            name='workspacemember',
            table='core_organizationuser',
        ),
        migrations.AlterModelTable(
            name='integration',
            table='core_integration',
        ),
        migrations.AlterModelTable(
            name='notificationsettings',
            table='core_notificationsettings',
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='core_userprofile',
        ),
        # Step 7: Create new WorkspaceInvitation model
        migrations.CreateModel(
            name='WorkspaceInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('user', 'User')], default='user', max_length=20)),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=core.models.get_invitation_expiry)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='core.workspace')),
            ],
            options={
                'db_table': 'core_workspaceinvitation',
            },
        ),
    ]
