# Generated by Django 5.2.10 on 2026-01-23 09:07

from django.db import migrations


def migrate_userprofiles_to_workspace_members(apps, schema_editor):
    """
    Migrate existing UserProfile data to WorkspaceMember records.

    This migration:
    1. Updates any existing WorkspaceMember records with 'member' or 'viewer'
       roles to 'user' (the new role name)
    2. For each UserProfile that has a workspace, creates a WorkspaceMember
       record with role='owner' if one doesn't already exist
    """
    UserProfile = apps.get_model("core", "UserProfile")
    WorkspaceMember = apps.get_model("core", "WorkspaceMember")

    # Step 1: Update existing WorkspaceMember records with old role names
    WorkspaceMember.objects.filter(role="member").update(role="user")
    WorkspaceMember.objects.filter(role="viewer").update(role="user")

    # Step 2: Migrate UserProfile records to WorkspaceMember
    for profile in UserProfile.objects.filter(workspace__isnull=False):
        # Check if a WorkspaceMember already exists for this user/workspace combo
        existing = WorkspaceMember.objects.filter(
            user=profile.user, workspace=profile.workspace
        ).first()

        if existing:
            # Member already exists, just ensure is_active is True
            if not existing.is_active:
                existing.is_active = True
                existing.save(update_fields=["is_active"])
        else:
            # Create new WorkspaceMember with owner role
            WorkspaceMember.objects.create(
                user=profile.user,
                workspace=profile.workspace,
                role="owner",
                is_active=True,
            )


def reverse_migration(apps, schema_editor):
    """
    Reverse migration: Remove WorkspaceMember records that were auto-created.

    Note: This cannot fully reverse the migration since we don't track which
    WorkspaceMember records existed before vs. were created by this migration.
    It's a best-effort reversal.
    """
    # We don't delete anything on reverse since we can't reliably determine
    # which records were created by this migration vs. existed before.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_workspace_rename_and_invitation"),
    ]

    operations = [
        migrations.RunPython(
            migrate_userprofiles_to_workspace_members,
            reverse_code=reverse_migration,
        ),
    ]
