# Generated by Django 5.2.10 on 2026-01-23 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_migrate_userprofile_to_workspacemember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspaceinvitation',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='workspacemember',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.workspace'),
        ),
    ]
