# Generated by Django 5.2.10 on 2026-01-23 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_email_index_to_invitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='slack_user_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
