# Generated by Django 5.2.10 on 2026-01-24 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_logo_storage_to_company'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['name'], name='company_name_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['created_at'], name='company_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['-updated_at'], name='company_updated_at_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['logo_content_type', '-updated_at'], name='company_logo_updated_idx'),
        ),
    ]
