# Generated by Django 5.2.10 on 2026-01-24 07:42
"""Remove 'trial' as a subscription plan.

Trial is now only a subscription STATUS (managed by Stripe for paid plans),
not a separate PLAN. Users trialing paid plans will have:
- subscription_plan = "basic", "pro", or "enterprise"
- subscription_status = "trial"

Existing users on the 'trial' plan are migrated to 'free' plan.
"""

from django.db import migrations, models


def migrate_trial_to_free(apps, schema_editor):
    """Migrate existing workspaces from trial plan to free plan."""
    # The model is Workspace (db_table is core_organization for backwards compat)
    Workspace = apps.get_model("core", "Workspace")
    updated = Workspace.objects.filter(subscription_plan="trial").update(
        subscription_plan="free"
    )
    if updated:
        print(f"  Migrated {updated} workspace(s) from 'trial' to 'free' plan")


def reverse_migrate_trial_to_free(apps, schema_editor):
    """Reverse migration - no-op as we can't know which were originally trial."""
    pass


def delete_trial_plan_record(apps, schema_editor):
    """Delete the trial Plan record from the database."""
    Plan = apps.get_model("core", "Plan")
    deleted, _ = Plan.objects.filter(name="trial").delete()
    if deleted:
        print("  Deleted trial Plan record")


def recreate_trial_plan_record(apps, schema_editor):
    """Recreate the trial Plan record (for rollback)."""
    Plan = apps.get_model("core", "Plan")
    Plan.objects.get_or_create(
        name="trial",
        defaults={
            "display_name": "14-Day Trial",
            "description": "Try all features free for 14 days",
            "price_monthly": 0.00,
            "price_yearly": 0.00,
            "max_users": 1,
            "max_integrations": 3,
            "max_monthly_notifications": 1000,
            "features": [
                "Up to 1,000 notifications",
                "Basic integrations",
                "Email support",
            ],
            "stripe_price_id_monthly": "",
            "stripe_price_id_yearly": "",
            "is_active": True,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_company_indexes'),
    ]

    operations = [
        # First, migrate existing data before changing choices
        migrations.RunPython(
            migrate_trial_to_free,
            reverse_migrate_trial_to_free,
        ),
        # Delete the trial Plan record
        migrations.RunPython(
            delete_trial_plan_record,
            recreate_trial_plan_record,
        ),
        # Then alter the fields to remove trial from choices
        migrations.AlterField(
            model_name='usagelimit',
            name='plan',
            field=models.CharField(choices=[('free', 'Free Plan'), ('basic', 'Basic Plan - $29/month'), ('pro', 'Pro Plan - $99/month'), ('enterprise', 'Enterprise Plan - $299/month')], max_length=20),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='subscription_plan',
            field=models.CharField(choices=[('free', 'Free Plan'), ('basic', 'Basic Plan - $29/month'), ('pro', 'Pro Plan - $99/month'), ('enterprise', 'Enterprise Plan - $299/month')], default='free', max_length=20),
        ),
    ]
