# Generated by Django 5.2.10 on 2026-01-24 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_remove_trial_plan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspace",
            name="subscription_status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("trial", "Trial"),
                    ("suspended", "Suspended"),
                    ("cancelled", "Cancelled"),
                ],
                default="active",
                max_length=20,
            ),
        ),
    ]
