# Generated by Django 5.2.10 on 2026-01-24 14:11
"""Fix impossible state: free plan with trial status.

Free plan users should have 'active' status, not 'trial'.
Trial status is only valid for paid plans (basic, pro, enterprise).
"""

from django.db import migrations


def fix_free_trial_workspaces(apps, schema_editor):
    """Fix workspaces that have free plan but trial status."""
    Workspace = apps.get_model("core", "Workspace")
    updated = Workspace.objects.filter(
        subscription_plan="free",
        subscription_status="trial",
    ).update(subscription_status="active")
    if updated:
        print(f"  Fixed {updated} workspace(s) with free plan + trial status")


def reverse_fix_free_trial_workspaces(apps, schema_editor):
    """Reverse migration - no-op as we can't know which were originally trial."""
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_fix_subscription_status_default"),
    ]

    operations = [
        migrations.RunPython(
            fix_free_trial_workspaces,
            reverse_fix_free_trial_workspaces,
        ),
    ]
