# Generated by Django 5.2.10 on 2026-01-24 20:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_fix_free_plan_trial_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspace",
            name="subscription_plan",
            field=models.CharField(
                choices=[
                    ("free", "Free Plan"),
                    ("basic", "Basic Plan - $29/month"),
                    ("pro", "Pro Plan - $99/month"),
                    ("enterprise", "Enterprise Plan - $299/month"),
                ],
                default="free",
                max_length=100,
            ),
        ),
    ]
