# Generated by Django 5.2.10 on 2026-01-25 08:42

import os

from django.db import migrations


def create_stripe_billing_integration(apps, schema_editor):
    """Create GlobalBillingIntegration for Stripe billing webhooks."""
    GlobalBillingIntegration = apps.get_model("core", "GlobalBillingIntegration")

    # Get webhook secret from environment (required for production)
    webhook_secret = os.environ.get("NOTIPUS_STRIPE_WEBHOOK_SECRET", "")

    GlobalBillingIntegration.objects.get_or_create(
        integration_type="stripe_billing",
        defaults={
            "webhook_secret": webhook_secret,
            "is_active": True,
            "oauth_credentials": {},
            "integration_settings": {},
        },
    )


def remove_stripe_billing_integration(apps, schema_editor):
    """Remove the Stripe billing integration."""
    GlobalBillingIntegration = apps.get_model("core", "GlobalBillingIntegration")
    GlobalBillingIntegration.objects.filter(integration_type="stripe_billing").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_increase_subscription_plan_length"),
    ]

    operations = [
        migrations.RunPython(
            create_stripe_billing_integration,
            remove_stripe_billing_integration,
        ),
    ]
