# Generated by Django 5.2.10 on 2026-01-28 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_add_stripe_billing_integration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='integration_type',
            field=models.CharField(choices=[('stripe_customer', 'Stripe Customer Payments'), ('shopify', 'Shopify Ecommerce'), ('chargify', 'Chargify / Maxio Advanced Billing'), ('zendesk', 'Zendesk Support'), ('slack_notifications', 'Slack Notifications')], max_length=50),
        ),
    ]
