# Generated by Django 5.2.10 on 2026-01-28 17:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_add_stripe_billing_integration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='integration_type',
            field=models.CharField(choices=[('stripe_customer', 'Stripe Customer Payments'), ('shopify', 'Shopify Ecommerce'), ('chargify', 'Chargify / Maxio Advanced Billing'), ('slack_notifications', 'Slack Notifications'), ('hunter_enrichment', 'Hunter.io Email Enrichment')], max_length=50),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, default='', max_length=100)),
                ('last_name', models.CharField(blank=True, default='', max_length=100)),
                ('position', models.CharField(blank=True, default='', max_length=255)),
                ('seniority', models.CharField(blank=True, default='', max_length=50)),
                ('company_domain', models.CharField(blank=True, default='', max_length=255)),
                ('linkedin_url', models.URLField(blank=True, default='', max_length=500)),
                ('twitter_handle', models.CharField(blank=True, default='', max_length=100)),
                ('github_handle', models.CharField(blank=True, default='', max_length=100)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('hunter_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'People',
                'indexes': [models.Index(fields=['created_at'], name='person_created_at_idx'), models.Index(fields=['-updated_at'], name='person_updated_at_idx')],
            },
        ),
    ]
