# Generated by Django 5.2.10 on 2026-01-28 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_add_person_model_and_hunter_integration'),
        ('core', '0018_add_zendesk_integration_type'),
    ]

    operations = [
    ]
